In [3]:
import pandas as pd
# Read Dataset
data = pd.read_csv("student_data.csv")
data.head()


,StudyHours,SleepHours,PlayingHours,Pass
0,8,7,1,1
1,7,8,2,1
2,6,6,3,1
3,5,7,2,1
4,9,6,1,1


In [4]:
X = data[['StudyHours',
          'SleepHours',
          'PlayingHours']]
y = data['Pass']
print(X)
print(y)

   StudyHours  SleepHours  PlayingHours
0           8           7             1
1           7           8             2
2           6           6             3
3           5           7             2
4           9           6             1
5           4           5             5
6           3           6             6
7           2           5             7
8           1           6             8
9           5           4             6
0    1
1    1
2    1
3    1
4    1
5    0
6    0
7    0
8    0
9    0
Name: Pass, dtype: int64


In [7]:
!pip install tensorflow

   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/351.2 MB 3.4 MB/s eta 0:01:43
   ---------------------------------------- 1.8/351.2 MB 5.5 MB/s eta 0:01:05
   ---------------------------------------- 3.4/351.2 MB 6.2 MB/s eta 0:00:57
    --------------------------------------- 4.5/351.2 MB 6.1 MB/s eta 0:00:58
    --------------------------------------- 5.8/351.2 MB 6.1 MB/s eta 0:00:57
    --------------------------------------- 6.8/351.2 MB 6.0 MB/s eta 0:00:58
    --------------------------------------- 7.9/351.2 MB 5.9 MB/s eta 0:00:58
   - -------------------------------------- 9.2/351.2 MB 5.8 MB/s eta 0:01:00
   - -------------------------------------- 10.0/351.2 MB 5.7 MB/s eta 0:01:00
   - -------------------------------------- 11.0/351.2 MB 5.5 MB/s eta 0:01:02
   - -------------------------------------- 12.1/351.2 MB 5.6 MB/s eta 0:01:02
   - -------------------------------------- 13.1/351.2 MB 5.5 MB/s e

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.35.1 which is incompatible.


In [9]:
# Single neuron and step activation function
import tensorflow as tf

model = tf.keras.Sequential([

    tf.keras.layers.Dense(
        units=1,
        activation='linear',
        input_shape=(3,)
    )

])

prediction = model(X)

step_output = tf.where(prediction > 0, 1, 0)

print(step_output)

tf.Tensor(
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]], shape=(10, 1), dtype=int32)


In [10]:
# Single Neuron, Sigmoid activation 
import tensorflow as tf

model = tf.keras.Sequential([

    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid',
        input_shape=(3,)
    )

])

output = model(X)

print(output)

tf.Tensor(
[[0.39301983]
 [0.8299021 ]
 [0.5888435 ]
 [0.9235017 ]
 [0.07514072]
 [0.76006025]
 [0.9597893 ]
 [0.9538498 ]
 [0.9936199 ]
 [0.27314857]], shape=(10, 1), dtype=float32)


In [11]:
#multi neuron step activation
import tensorflow as tf

model = tf.keras.Sequential([

    tf.keras.layers.Dense(
        units=4,
        activation='linear',
        input_shape=(3,)
    ),

    tf.keras.layers.Dense(
        units=1,
        activation='linear'
    )

])

prediction = model(X)

step_output = tf.where(prediction > 0, 1, 0)

print(step_output)

tf.Tensor(
[[1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]], shape=(10, 1), dtype=int32)


In [12]:
# Multi neuron, sigmoid activation
import tensorflow as tf

model = tf.keras.Sequential([

    tf.keras.layers.Dense(
        units=4,
        activation='sigmoid',
        input_shape=(3,)
    ),

    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid'
    )

])

output = model(X)

print(output)

tf.Tensor(
[[0.4154041 ]
 [0.42335638]
 [0.4060179 ]
 [0.44920808]
 [0.40450236]
 [0.39437962]
 [0.3925038 ]
 [0.37646952]
 [0.37156072]
 [0.3898202 ]], shape=(10, 1), dtype=float32)
