**Mean Absolute Error (MAE)**

In [7]:
import pandas as pd
import tensorflow as tf

# Read Dataset
data = pd.read_csv("student_file.csv")
print(data.head())

X = data[['StudyHours']].values
y = data['Marks'].values

# Forward Pass Model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid',
        input_shape=(1,)
    )
])

# Forward Pass
prediction = model(X)
print("Predictions")
print(prediction.numpy())

# Calculate MAE
mae = tf.reduce_mean(tf.abs(y.reshape(-1,1) - prediction))

print("\nMAE Loss")
print(mae.numpy())

   StudyHours  Marks
0           1     10
1           2     20
2           3     30
3           4     40
4           5     50
Predictions
[[2.2466627e-01]
 [7.7461004e-02]
 [2.3752404e-02]
 [7.0007690e-03]
 [2.0387301e-03]
 [5.9161359e-04]
 [1.7150231e-04]
 [4.9701779e-05]
 [1.4402448e-05]
 [4.1734015e-06]]

MAE Loss
54.966423


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


**Mean Squared Error**

In [8]:
import pandas as pd
import tensorflow as tf

# Read Dataset
data = pd.read_csv("student_file.csv")
print(data.head())

X = data[['StudyHours']].values
y = data['Marks'].values

# Forward Pass Model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid',
        input_shape=(1,)
    )
])

# Forward Pass
prediction = model(X)

print("Predictions")
print(prediction.numpy())

# Calculate MSE
mse = tf.reduce_mean(
    tf.square(y.reshape(-1,1)-prediction)
)

print("MSE =",mse.numpy())


   StudyHours  Marks
0           1     10
1           2     20
2           3     30
3           4     40
4           5     50
Predictions
[[0.6956497 ]
 [0.83934104]
 [0.92272776]
 [0.96465683]
 [0.98422354]
 [0.9930359 ]
 [0.9969412 ]
 [0.99865943]
 [0.9994131 ]
 [0.9997431 ]]
MSE = 3743.211


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


**Huber's Loss**

In [9]:
import pandas as pd
import tensorflow as tf

data = pd.read_csv("student_file.csv")

X = data[['StudyHours']].values
y = data['Marks'].values

model = tf.keras.Sequential([
    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid',
        input_shape=(1,)
    )
])

prediction = model(X)

huber = tf.keras.losses.Huber(delta=1.0)

loss = huber(y.reshape(-1,1),prediction)

print("Huber Loss")
print(loss.numpy())

Huber Loss
53.536915


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


**Binary Cross Entropy**

In [5]:
import pandas as pd
import tensorflow as tf

data = pd.read_csv("student_result.csv")
print(data.head())

X = data[['Study','Sleep','Play']].values
y = data['Result'].values

model = tf.keras.Sequential([

    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid',
        input_shape=(3,)
    )

])

prediction = model(X)

print("Predictions")
print(prediction.numpy())

bce = tf.keras.losses.BinaryCrossentropy()

loss = bce(y.reshape(-1,1),prediction)

print("\nBinary Cross Entropy")
print(loss.numpy())

   Study  Sleep  Play  Result
0      8      7     1       1
1      7      8     2       1
2      5      6     3       1
3      4      6     4       0
4      3      5     5       0
Predictions
[[0.9910586 ]
 [0.98557174]
 [0.872506  ]
 [0.7125738 ]
 [0.34551787]
 [0.10105859]]

Binary Cross Entropy
0.3228564


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


**Categorical Cross Entropy**

In [6]:
import pandas as pd
import tensorflow as tf

data = pd.read_csv("iris.csv")

X = data[['Length',
          'Width',
          'PetalLength',
          'PetalWidth']].values

y = tf.keras.utils.to_categorical(
        data['Class'],
        num_classes=3
)

model = tf.keras.Sequential([

    tf.keras.layers.Dense(
        units=3,
        activation='softmax',
        input_shape=(4,)
    )

])

prediction = model(X)

print(prediction.numpy())

cce = tf.keras.losses.CategoricalCrossentropy()

loss = cce(y,prediction)

print("\nCategorical Cross Entropy")

print(loss.numpy())

[[0.03076085 0.45910716 0.51013196]
 [0.38031054 0.4599434  0.15974604]
 [0.4503004  0.4244447  0.12525499]
 [0.03655243 0.4844153  0.47903225]
 [0.43090686 0.4725658  0.0965273 ]
 [0.18964998 0.6670993  0.14325066]]

Categorical Cross Entropy
2.0645537


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
